### ISSUE TITLE
Importer error - doImport not defined

### ISSUE THREAD

**Issue by badtumshie** [SergeyMakeev/Ninja-Ripper-Maya-Importer-#1]
Hi, whenever i try to import a rip file the Maya console gives me this error:
# Error: NameError: file <maya console> line 1: name 'doImport' is not defined
Is there any way to fix this?

**Comment by SergeyMakeev** [comment]
This is very strange behaviour. Could you please enable "Show Stack Trace" inside a Script Editor and attach resulting history output to issue?

**Comment by Jigamesh** [comment]
Hello, having the same error here.

NinjaImporter.py
Error: NameError: file <maya console> line 1: name 'NinjaImporter' is not defined # 

with stack trace

NinjaImporter.py

Error: name 'NinjaImporter' is not defined
Traceback (most recent call last):
 File "<maya console>", line 1, in <module>
 NameError: name 'NinjaImporter' is not defined # 

using maya 2017

**Comment by Jigamesh** [comment]
im getting this error after source script

Error: line 0: expected an indented block
 File "<maya console>", line 359
  showImportDialog(len(filesToImport))
                    ^
IndentationError: expected an indented block
